markdown: rdiscount
permalink: /:title/
url: http://froghui.github.io
name: froghui homepage
author: froghui
qq: 46898228
email: froghui2002@hotmail.com
weibo: froghui2002@hotmail.com
github: froghui
pygments: true
safe: true
paginate: 20
about: "关注linux，云计算和devops"
